// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoCcJ56thaDm9yqiU_ZwjxwDgsWJ3hAmQ',
    appId: '1:180153828961:web:04025c9d29fa74608b0c20',
    messagingSenderId: '180153828961',
    projectId: 'pharmacy-2fbba',
    authDomain: 'pharmacy-2fbba.firebaseapp.com',
    storageBucket: 'pharmacy-2fbba.appspot.com',
    measurementId: 'G-709S3E8339',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOTP9g9ykUXNz1gfrTh8Bjfm2S34aDjyI',
    appId: '1:180153828961:android:9127bcda1fa4ff8e8b0c20',
    messagingSenderId: '180153828961',
    projectId: 'pharmacy-2fbba',
    storageBucket: 'pharmacy-2fbba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhTv3_gyD_1ehTMXwBi2unS_x-DOgOXQ8',
    appId: '1:180153828961:ios:cea5a1df6959bdca8b0c20',
    messagingSenderId: '180153828961',
    projectId: 'pharmacy-2fbba',
    storageBucket: 'pharmacy-2fbba.appspot.com',
    iosClientId: '180153828961-81mg1r2reku6ietjkk2e7je29pqgn5ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhTv3_gyD_1ehTMXwBi2unS_x-DOgOXQ8',
    appId: '1:180153828961:ios:cea5a1df6959bdca8b0c20',
    messagingSenderId: '180153828961',
    projectId: 'pharmacy-2fbba',
    storageBucket: 'pharmacy-2fbba.appspot.com',
    iosClientId: '180153828961-81mg1r2reku6ietjkk2e7je29pqgn5ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoCcJ56thaDm9yqiU_ZwjxwDgsWJ3hAmQ',
    appId: '1:180153828961:web:fe8debd7f6f1835a8b0c20',
    messagingSenderId: '180153828961',
    projectId: 'pharmacy-2fbba',
    authDomain: 'pharmacy-2fbba.firebaseapp.com',
    storageBucket: 'pharmacy-2fbba.appspot.com',
    measurementId: 'G-8Y7J0RL1FB',
  );

}